version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - agentcoord-network
    environment:
      - API_BASE=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_BASE=htts://api.openai.com
      - OPENAI_API_KEY=
      - OPENAI_API_MODEL=gpt-4-turbo-preview
      - FAST_DESIGN_MODE=True
      - GROQ_API_KEY=
    networks:
      - agentcoord-network

networks:
  agentcoord-network:
    driver: bridge
